import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/Provider/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { getLocale } from "next-intl/server";
import QueryProvider from "@/components/Provider/QueryProvider";

const gMarketSans = localFont({
  src: [
    { path: "../public/fonts/GmarketSansTTFLight.ttf", weight: "300" },
    { path: "../public/fonts/GmarketSansTTFMedium.ttf", weight: "400" },
    { path: "../public/fonts/GmarketSansTTFBold.ttf", weight: "700" },
  ],
  variable: "--font-gMarket-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // initializing the intl client
  const locale = await getLocale();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`${gMarketSans.variable} antialiased`}>
        <QueryProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <Toaster richColors />
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
